### ISSUE TITLE
Create a component that displays temperature data over the last 24hours

### ISSUE THREAD

**Issue by sbland** [jonathandw743/myreactapp2#1]
We have the following api function that can request data ...

``` ts
import { getDataFetch } from "./apiHelpers";

import { SERVER_URL } from "../config";

export interface apiMonitorDataReturn {
  data: {date: Date, val: number}[];
  startTime: Date,
  endTime: Date,
}

export enum Metric {
  TEMPERATURE = "temperature",
  CO2 = "co2",
}

export const apiMonitorData = {
  get: async (metric: Metric, startTime = null, endTime = null) => {
    const startTimeQ = startTime || new Date().setHours(new Date().getHours() - 24);
    const endTimeQ = endTime || new Date();
    const startTimeQuery = `start=${startTimeQ}`;
    const endTimeQuery = `end=${endTimeQ}`;
    const query = [startTimeQuery, endTimeQuery].filter((f) => f).join("&");

    let url = `${SERVER_URL}/query/MonitorData/${metric}`;
    url = query ? `${url}?${query}` : url;
    return getDataFetch<apiMonitorDataReturn>(url).then((data) => ({ data, startTime: startTimeQ, endTime: endTimeQ }));
  },
};


```

This basically takes a metric and optional start and end time. It will then return an object that has the date along with the actual start and end time.
The data is a list of objects where each object has a value and timestamp.

What we need is a react component that will take this data and product a plot.

You will need the following libraries.
- Echarts `yarn add echarts echarts-for-react`

Then test the library works by replacing the code in `components/container.jsx` with the example here: https://github.com/hustcc/echarts-for-react/blob/master/docs/examples/simple.md
(Sorry the data in it is in Kanji!)

FYI run your app with `yarn start`

**Comment by sbland** [comment]
Example of data ...

``` json

{
    "data": [
        {
            "time": "2022-07-20T03:00:00",
            "val": 18.2
        },
        {
            "time": "2022-07-20T04:00:00",
            "val": 18.9
        }
        {
            "time": "2022-07-20T05:00:00",
            "val": 19.4
        }
    ]
}
```

**Comment by jonathandw743** [comment]
I have taken the sample data and created a graph using react echarts
